spring:
  h2:
    console:
      enabled: true
      path: /h2-console


  jackson:
    serialization:
      fail-on-empty-beans: false
jwt:
  secret: HUmUJBkkEFUwW77GdIm3PHhcbiOEga4V
token:
  validity: 3600000

document:
  upload-directory: invoices

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics

